modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="aris_random_additions"
version="2.1.1"
displayName="Ari's Random Additions"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="nimsolated, MCreator"
description="Random Additions by Ari. Created with MCreator."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.aris_random_additions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.aris_random_additions]]
    modId="pehkui"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration